In [1]:
import pandas as pd

In [2]:
df = pd.read_excel('./102_111StdInfo1Acdm.xlsx')

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 126451 entries, 0 to 126450
Data columns (total 21 columns):
 #   Column         Non-Null Count   Dtype
---  ------         --------------   -----
 0   日間部/進推代碼       126451 non-null  object
 1   日間部/進推         126451 non-null  object
 2   學制代碼           126451 non-null  object
 3   學制             126451 non-null  object
 4   學制/系科代碼        126451 non-null  object
 5   學制/系科          126451 non-null  object
 6   學制/系科/年級/班級代碼  126451 non-null  object
 7   學制/系科/年級/班級    126451 non-null  object
 8   年級             126451 non-null  int64
 9   學號             126451 non-null  object
 10  性別             126451 non-null  object
 11  學年度            126451 non-null  int64
 12  學期             126451 non-null  int64
 13  在學狀況           126451 non-null  object
 14  排名             124823 non-null  float64
 15  入學年度           126451 non-null  int64
 16  入學管道代碼         126451 non-null  int64
 17  入學管道           126451 non-null  object
 18  畢業學校類別代碼       126451 non-null  int64
 19  畢業學校代碼         126451 non-null  object
 20  畢業學校           126451 non-null  object
dtypes: float64(1), int64(6), object(14)
memory usage: 20.3+ MB

In [5]:
df.columns

Index(['日間部/進推代碼', '日間部/進推', '學制代碼', '學制', '學制/系科代碼', '學制/系科', '學制/系科/年級/班級代碼',
       '學制/系科/年級/班級', '年級', '學號', '性別', '學年度', '學期', '在學狀況', '排名', '入學年度',
       '入學管道代碼', '入學管道', '畢業學校類別代碼', '畢業學校代碼', '畢業學校'],
      dtype='object')

In [6]:
df.head()

,日間部/進推代碼,日間部/進推,學制代碼,學制,學制/系科代碼,學制/系科,學制/系科/年級/班級代碼,學制/系科/年級/班級,年級,學號,...,學年度,學期,在學狀況,排名,入學年度,入學管道代碼,入學管道,畢業學校類別代碼,畢業學校代碼,畢業學校
0,D,日間部,3,日二技,301,二技會資,30130A,二技會資三甲,3,11031031,...,111,2,在學,6.0,111,69,申請入學,5,0051,國立臺北商業大學
1,D,日間部,3,日二技,301,二技會資,30130A,二技會資三甲,3,11031031,...,110,2,在學,10.0,111,69,申請入學,5,0051,國立臺北商業大學
2,D,日間部,3,日二技,301,二技會資,30130A,二技會資三甲,3,11031031,...,111,1,在學,8.0,111,69,申請入學,5,0051,國立臺北商業大學
3,D,日間部,3,日二技,301,二技會資,30130A,二技會資三甲,3,11031031,...,110,1,在學,14.0,111,69,申請入學,5,0051,國立臺北商業大學
4,D,日間部,3,日二技,301,二技會資,30190A,二技會資九甲,9,10131001,...,101,1,畢業,1.0,103,78,技優保送,5,0142,國立臺北商業技術學院

In [13]:
df = df[['學年度', '學制', '學制/系科']]

In [17]:
df.to_csv('./sunburst.csv',index=False)

In [14]:
df.head()

   學年度   學制 學制/系科
0  111  日二技  二技會資
1  110  日二技  二技會資
2  111  日二技  二技會資
3  110  日二技  二技會資
4  101  日二技  二技會資

In [15]:
filtered_df = df[df['學年度'] == 111]
student_counts = filtered_df.groupby(['學制', '學制/系科']).size().reset_index(name='Count')

In [16]:
student_counts

        學制             學制/系科  Count
0      博士班           財經學院博士班      2
1     多元專長          多元專長培力課程      2
2      日二技              二技企管     63
3      日二技              二技創科     57
4      日二技              二技商務     65
5      日二技              二技商設     85
6      日二技              二技應外     56
7      日二技              二技數媒      2
8      日二技              二技會資     63
9      日二技              二技菁英      8
10     日二技              二技財稅     63
11     日二技              二技財金     72
12     日二技              二技資管     63
13     日五專              五專企管    100
14     日五專              五專國貿     92
15     日五專              五專應外     88
16     日五專        五專會計與資料科學科    102
17     日五專              五專財稅     75
18     日五專              五專財金     96
19     日五專              五專資管     67
20     日四技              四技企管    223
21     日四技              四技創科     78
22     日四技              四技商務    203
23     日四技              四技商設     95
24     日四技              四技應外     72
25     日四技              四技數媒    100
26     日四技              四技會資    189
27     日四技              四技財稅    162
28     日四技              四技財金     89
29     日四技              四技資管     65
30  碩士在職專班     企業管理系EMBA在職專班     41
31  碩士在職專班       境外碩士在職班(春季)      1
32     碩士班          企業管理系碩士班     27
33     碩士班               創研所     29
34     碩士班          國際商務系碩士班     29
35     碩士班           會計財稅碩士班      9
36     碩士班          會計資訊系碩士班     18
37     碩士班          財務金融系碩士班     26
38     碩士班          財政稅務系碩士班     15
39     碩士班   貿易實務法律暨談判碩士學位學程     13
40     碩士班               資研所     17
41     碩士班  資訊管理系人工智慧與商業應用碩士      8
42     進二專             進二專企管    223
43     進二專             進二專外語     36
44     進二技             進二技企管    216
45     進二技             進二技應外    149
46     進二技             進二技會資     87
47     進二技             進二技財稅     86
48     進二技             進二技財金     93
49     進二技             進二技資管    137
50     進四技             進四技企管     72
51     進四技             進四技商務     58
52     進四技             進四技數媒     56
53     進四技             進四技會資     58
54     進四技             進四技財金     56
55     進四技             進四技資管    107